// Generated by sylc. MVP SystemVerilog subset.

module Child (
    input x,
    output y
);
  assign y = x;
endmodule

module Top (
    input x,
    output y
);
  wire tmp;
  Child child_inst (.x(x), .y(tmp));
  assign y = tmp;
endmodule

