#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub(super) struct SvDesign {
    pub(super) modules: Vec<SvModule>,
}

impl SvDesign {
    pub(super) fn new(modules: Vec<SvModule>) -> Self {
        Self { modules }
    }

    pub(super) fn debug_dump(&self) -> String {
        let modules = self
            .modules
            .iter()
            .map(|module| module.name.clone())
            .collect::<Vec<_>>()
            .join(", ");
        format!("sv_ast modules={} [{}]", self.modules.len(), modules)
    }

    pub(super) fn emit_text(&self) -> String {
        let mut out = String::new();
        out.push_str("// Generated by sylc. MVP SystemVerilog subset.\n\n");
        for module in &self.modules {
            module.emit_into(&mut out);
            out.push('\n');
        }
        out
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub(super) struct SvModule {
    pub(super) name: String,
    pub(super) params: Vec<SvParam>,
    pub(super) ports: Vec<SvPort>,
    pub(super) items: Vec<SvItem>,
}

impl SvModule {
    pub(super) fn new(
        name: impl Into<String>,
        params: Vec<SvParam>,
        ports: Vec<SvPort>,
        items: Vec<SvItem>,
    ) -> Self {
        Self {
            name: name.into(),
            params,
            ports,
            items,
        }
    }

    fn emit_into(&self, out: &mut String) {
        out.push_str(&format!("module {}", self.name));
        if !self.params.is_empty() {
            out.push_str(" #(\n");
            for (idx, param) in self.params.iter().enumerate() {
                let comma = if idx + 1 == self.params.len() {
                    ""
                } else {
                    ","
                };
                out.push_str(&format!(
                    "    parameter {} = {}{}\n",
                    param.name, param.default, comma
                ));
            }
            out.push(')');
        }
        if self.ports.is_empty() {
            out.push_str(" ();\n");
        } else {
            out.push_str(" (\n");
            for (idx, port) in self.ports.iter().enumerate() {
                let comma = if idx + 1 == self.ports.len() { "" } else { "," };
                out.push_str(&format!(
                    "    {} {}{}{}\n",
                    port.direction.keyword(),
                    SvRange::new(&port.width).prefix(),
                    port.name,
                    comma
                ));
            }
            out.push_str(");\n");
        }
        for item in &self.items {
            item.emit_into(out, 2);
        }
        out.push_str("endmodule\n");
    }
}

struct SvRange<'a> {
    width: &'a str,
}

impl<'a> SvRange<'a> {
    fn new(width: &'a str) -> Self {
        Self { width }
    }

    fn prefix(&self) -> String {
        if self.width == "1" {
            String::new()
        } else {
            format!("[({})-1:0] ", self.width)
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub(super) struct SvParam {
    pub(super) name: String,
    pub(super) default: String,
}

impl SvParam {
    pub(super) fn new(name: impl Into<String>, default: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            default: default.into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub(super) struct SvPort {
    pub(super) direction: SvDirection,
    pub(super) width: String,
    pub(super) name: String,
}

impl SvPort {
    pub(super) fn new(
        direction: SvDirection,
        width: impl Into<String>,
        name: impl Into<String>,
    ) -> Self {
        Self {
            direction,
            width: width.into(),
            name: name.into(),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub(super) enum SvDirection {
    Input,
    Output,
}

impl SvDirection {
    fn keyword(self) -> &'static str {
        match self {
            Self::Input => "input",
            Self::Output => "output",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub(super) enum SvItem {
    LocalParam {
        name: String,
        value: SvExpr,
    },
    Wire {
        width: String,
        name: String,
    },
    Reg {
        width: String,
        name: String,
    },
    Assign {
        lhs: SvExpr,
        rhs: SvExpr,
    },
    AlwaysReg {
        clock: SvExpr,
        target: SvExpr,
        reset: Option<SvReset>,
        next: SvExpr,
    },
    Instance(SvInstance),
    GenerateIf {
        cond: SvExpr,
        label: String,
        then_items: Vec<SvItem>,
        else_items: Vec<SvItem>,
    },
    GenerateFor {
        genvar: String,
        start: SvExpr,
        end: SvExpr,
        label: String,
        items: Vec<SvItem>,
    },
    InitialError {
        message: SvExpr,
    },
}

impl SvItem {
    fn emit_into(&self, out: &mut String, indent: usize) {
        let pad = " ".repeat(indent);
        match self {
            Self::LocalParam { name, value } => {
                out.push_str(&format!(
                    "{pad}localparam {name} = {};\n",
                    value.emit_text()
                ));
            }
            Self::Wire { width, name } => {
                out.push_str(&format!(
                    "{pad}wire {}{};\n",
                    SvRange::new(width).prefix(),
                    name
                ));
            }
            Self::Reg { width, name } => {
                out.push_str(&format!(
                    "{pad}reg {}{};\n",
                    SvRange::new(width).prefix(),
                    name
                ));
            }
            Self::Assign { lhs, rhs } => {
                out.push_str(&format!(
                    "{pad}assign {} = {};\n",
                    lhs.emit_text(),
                    rhs.emit_text()
                ));
            }
            Self::AlwaysReg {
                clock,
                target,
                reset,
                next,
            } => {
                out.push_str(&format!(
                    "{pad}always @(posedge {}) begin\n",
                    clock.emit_text()
                ));
                let target = target.emit_text();
                if let Some(reset) = reset {
                    out.push_str(&format!(
                        "{pad}  if ({}) {target} <= {};\n{pad}  else {target} <= {next};\n",
                        reset.condition.emit_text(),
                        reset.value.emit_text(),
                        next = next.emit_text()
                    ));
                } else {
                    out.push_str(&format!("{pad}  {target} <= {};\n", next.emit_text()));
                }
                out.push_str(&format!("{pad}end\n"));
            }
            Self::Instance(instance) => instance.emit_into(out, indent),
            Self::GenerateIf {
                cond,
                label,
                then_items,
                else_items,
            } => {
                out.push_str(&format!("{pad}generate\n"));
                out.push_str(&format!(
                    "{pad}  if ({}) begin : {label}\n",
                    cond.emit_text()
                ));
                for item in then_items {
                    item.emit_into(out, indent + 4);
                }
                if !else_items.is_empty() {
                    out.push_str(&format!("{pad}  end else begin : {label}_else\n"));
                    for item in else_items {
                        item.emit_into(out, indent + 4);
                    }
                }
                out.push_str(&format!("{pad}  end\n{pad}endgenerate\n"));
            }
            Self::GenerateFor {
                genvar,
                start,
                end,
                label,
                items,
            } => {
                out.push_str(&format!("{pad}genvar {genvar};\n"));
                out.push_str(&format!("{pad}generate\n"));
                out.push_str(&format!(
                    "{pad}  for ({genvar} = {}; {genvar} < {}; {genvar} = {genvar} + 1) begin : {label}\n",
                    start.emit_text(),
                    end.emit_text()
                ));
                for item in items {
                    item.emit_into(out, indent + 4);
                }
                out.push_str(&format!("{pad}  end\n{pad}endgenerate\n"));
            }
            Self::InitialError { message } => {
                out.push_str(&format!("{pad}initial begin\n"));
                out.push_str(&format!("{pad}  $error({});\n", message.emit_text()));
                out.push_str(&format!("{pad}end\n"));
            }
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub(super) enum SvExpr {
    Ident(String),
    Int(u64),
    Bool(bool),
    Str(String),
    Zero,
    Unary {
        op: SvUnaryOp,
        expr: Box<SvExpr>,
    },
    Binary {
        op: SvBinaryOp,
        left: Box<SvExpr>,
        right: Box<SvExpr>,
    },
    Mux {
        cond: Box<SvExpr>,
        then_value: Box<SvExpr>,
        else_value: Box<SvExpr>,
    },
    Select {
        mode: SvSelectMode,
        arms: Vec<SvSelectArm>,
        default: Box<SvExpr>,
    },
    Concat(Vec<SvExpr>),
    Slice {
        value: Box<SvExpr>,
        high: String,
        low: String,
    },
    IndexedPartSelect {
        value: Box<SvExpr>,
        index: Box<SvExpr>,
        width: String,
    },
    Index {
        value: Box<SvExpr>,
        index: Box<SvExpr>,
    },
    Call {
        name: String,
        args: Vec<SvExpr>,
    },
}

impl SvExpr {
    pub(super) fn emit_text(&self) -> String {
        let mut out = String::new();
        self.emit_into(&mut out);
        out
    }

    fn emit_into(&self, out: &mut String) {
        match self {
            Self::Ident(name) => out.push_str(name),
            Self::Int(value) => out.push_str(&value.to_string()),
            Self::Bool(value) => {
                if *value {
                    out.push_str("1'b1");
                } else {
                    out.push_str("1'b0");
                }
            }
            Self::Str(value) => {
                out.push('"');
                out.push_str(value);
                out.push('"');
            }
            Self::Zero => out.push_str("'0"),
            Self::Unary { op, expr } => {
                out.push('(');
                out.push_str(op.token());
                expr.emit_into(out);
                out.push(')');
            }
            Self::Binary { op, left, right } => {
                out.push('(');
                left.emit_into(out);
                out.push(' ');
                out.push_str(op.token());
                out.push(' ');
                right.emit_into(out);
                out.push(')');
            }
            Self::Mux {
                cond,
                then_value,
                else_value,
            } => {
                out.push('(');
                cond.emit_into(out);
                out.push_str(" ? ");
                then_value.emit_into(out);
                out.push_str(" : ");
                else_value.emit_into(out);
                out.push(')');
            }
            Self::Select {
                mode,
                arms,
                default,
            } => {
                out.push_str("/* ");
                out.push_str(mode.keyword());
                out.push_str(" */ ");
                Self::emit_select_chain(out, arms, default);
            }
            Self::Concat(parts) => {
                out.push('{');
                for (idx, part) in parts.iter().enumerate() {
                    if idx > 0 {
                        out.push_str(", ");
                    }
                    part.emit_into(out);
                }
                out.push('}');
            }
            Self::Slice { value, high, low } => {
                value.emit_into(out);
                out.push_str(&format!("[{high}:{low}]"));
            }
            Self::IndexedPartSelect {
                value,
                index,
                width,
            } => {
                value.emit_into(out);
                out.push('[');
                index.emit_into(out);
                out.push_str(&format!("*({width}) +: ({width})]"));
            }
            Self::Index { value, index } => {
                value.emit_into(out);
                out.push('[');
                index.emit_into(out);
                out.push(']');
            }
            Self::Call { name, args } => {
                out.push_str(name);
                out.push('(');
                for (idx, arg) in args.iter().enumerate() {
                    if idx > 0 {
                        out.push_str(", ");
                    }
                    arg.emit_into(out);
                }
                out.push(')');
            }
        }
    }

    fn emit_select_chain(out: &mut String, arms: &[SvSelectArm], default: &SvExpr) {
        if let Some((arm, rest)) = arms.split_first() {
            out.push('(');
            arm.guard.emit_into(out);
            out.push_str(" ? ");
            arm.value.emit_into(out);
            out.push_str(" : ");
            Self::emit_select_chain(out, rest, default);
            out.push(')');
        } else {
            default.emit_into(out);
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub(super) enum SvSelectMode {
    Priority,
    Unique,
}

impl SvSelectMode {
    fn keyword(self) -> &'static str {
        match self {
            Self::Priority => "priority",
            Self::Unique => "unique",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub(super) struct SvSelectArm {
    pub(super) guard: SvExpr,
    pub(super) value: SvExpr,
}

impl SvSelectArm {
    pub(super) fn new(guard: SvExpr, value: SvExpr) -> Self {
        Self { guard, value }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub(super) enum SvUnaryOp {
    Neg,
    Not,
}

impl SvUnaryOp {
    fn token(self) -> &'static str {
        match self {
            Self::Neg => "-",
            Self::Not => "!",
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub(super) enum SvBinaryOp {
    OrOr,
    AndAnd,
    Eq,
    NotEq,
    Lt,
    LtEq,
    Gt,
    GtEq,
    Add,
    Sub,
    Mul,
    Div,
    Rem,
    Shl,
    BitAnd,
    BitOr,
    BitXor,
}

impl SvBinaryOp {
    fn token(self) -> &'static str {
        match self {
            Self::OrOr => "||",
            Self::AndAnd => "&&",
            Self::Eq => "==",
            Self::NotEq => "!=",
            Self::Lt => "<",
            Self::LtEq => "<=",
            Self::Gt => ">",
            Self::GtEq => ">=",
            Self::Add => "+",
            Self::Sub => "-",
            Self::Mul => "*",
            Self::Div => "/",
            Self::Rem => "%",
            Self::Shl => "<<",
            Self::BitAnd => "&",
            Self::BitOr => "|",
            Self::BitXor => "^",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub(super) struct SvReset {
    pub(super) condition: SvExpr,
    pub(super) value: SvExpr,
}

impl SvReset {
    pub(super) fn new(condition: SvExpr, value: SvExpr) -> Self {
        Self { condition, value }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub(super) struct SvInstance {
    pub(super) module: String,
    pub(super) params: Vec<SvParamBind>,
    pub(super) name: String,
    pub(super) connections: Vec<SvConnection>,
}

impl SvInstance {
    pub(super) fn new(
        module: impl Into<String>,
        params: Vec<SvParamBind>,
        name: impl Into<String>,
        connections: Vec<SvConnection>,
    ) -> Self {
        Self {
            module: module.into(),
            params,
            name: name.into(),
            connections,
        }
    }

    fn emit_into(&self, out: &mut String, indent: usize) {
        let pad = " ".repeat(indent);
        out.push_str(&format!("{pad}{}", self.module));
        if !self.params.is_empty() {
            let params = self
                .params
                .iter()
                .map(|param| format!(".{}({})", param.name, param.value))
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!(" #({params})"));
        }
        let connections = self
            .connections
            .iter()
            .map(|conn| format!(".{}({})", conn.formal, conn.actual.emit_text()))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(" {} ({connections});\n", self.name));
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub(super) struct SvParamBind {
    pub(super) name: String,
    pub(super) value: String,
}

impl SvParamBind {
    pub(super) fn new(name: impl Into<String>, value: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            value: value.into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub(super) struct SvConnection {
    pub(super) formal: String,
    pub(super) actual: SvExpr,
}

impl SvConnection {
    pub(super) fn new(formal: impl Into<String>, actual: SvExpr) -> Self {
        Self {
            formal: formal.into(),
            actual,
        }
    }
}
